(() => {
  "use strict";

  const JOB_PATH = /^\/[^/]+\/[^/]+\/actions\/runs\/\d+\/job\/\d+\/?$/;
  const INITIAL_LOAD_SIZE = 2 * 1024 * 1024;

  interface NavigationEvent {
    url: URL;
    previousUrl: URL | null;
  }

  type NavigationCallback = (navigation: NavigationEvent) => void;
  type WindowWithNavigation = Window & { navigation?: EventTarget };

  interface JobStep {
    log_url: string;
    length?: Promise<number>;
    contentByLine?: Promise<string[]>;
  }

  interface LogWorkerResponse {
    type: "result" | "error";
    lines?: string[];
    error?: string;
  }

  interface ChromeRuntime {
    runtime: { getURL(path: string): string };
  }

  const extensionChrome = (
    globalThis as typeof globalThis & { chrome: ChromeRuntime }
  ).chrome;
  function contentRange(response: Response): { start: number; total: number } {
    const header = response.headers.get("content-range");
    const match = header?.match(/^bytes (\d+)-(\d+)\/(\d+)$/i);
    if (!match) {
      return {
        start: 0,
        total: Number(response.headers.get("content-length") ?? 0),
      };
    }

    return { start: Number(match[1]), total: Number(match[3]) };
  }

  async function parseLogResponse(response: Response): Promise<string[]> {
    if (!response.ok) {
      throw new Error(`Log request failed with HTTP ${response.status}`);
    }
    if (!response.body) throw new Error("Log response did not include a body");

    const hostUrl = extensionChrome.runtime.getURL("worker-host.html");
    const hostOrigin = new URL(hostUrl).origin;
    const host = document.createElement("iframe");
    host.hidden = true;
    host.src = hostUrl;

    const hostReady = new Promise<void>((resolve, reject) => {
      host.addEventListener("load", () => resolve(), { once: true });
      host.addEventListener("error", () => {
        reject(new Error("Unable to load the log parser worker host"));
      }, { once: true });
    });
    document.documentElement.append(host);

    const result = new Promise<string[]>((resolve, reject) => {
      const handleResult = (event: MessageEvent<LogWorkerResponse>): void => {
        if (event.source !== host.contentWindow || event.origin !== hostOrigin) return;
        window.removeEventListener("message", handleResult);

        const message = event.data;
        if (message.type === "error") {
          reject(new Error(message.error ?? "Unknown log parser error"));
        } else {
          resolve(message.lines ?? []);
        }
      };
      window.addEventListener("message", handleResult);
    });

    try {
      await hostReady;
      const { start } = contentRange(response);
      host.contentWindow!.postMessage(
        { stream: response.body, discardFirstLine: start > 0 },
        hostOrigin,
        [response.body],
      );
      return await result;
    } finally {
      host.remove();
    }
  }

  /**
   * Runs callback once for the initial URL and once for each committed URL
   * transition. GitHub emits more than one event for a soft navigation, so URL
   * delivery is deduplicated independently from the event that detected it.
   */
  function onNavigation(callback: NavigationCallback): () => void {
    let deliveredUrl: string | null = null;
    let scheduled = false;

    const deliver = (): void => {
      scheduled = false;

      const nextUrl = location.href;
      if (nextUrl === deliveredUrl) return;

      const previousUrl = deliveredUrl ? new URL(deliveredUrl) : null;
      deliveredUrl = nextUrl;
      callback({ url: new URL(nextUrl), previousUrl });
    };

    // Coalesce history, Turbo, Navigation API, and DOM signals generated by a
    // single GitHub navigation into one callback at the next rendered frame.
    const schedule = (): void => {
      if (scheduled || location.href === deliveredUrl) return;
      scheduled = true;
      if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", deliver, { once: true });
      } else {
        requestAnimationFrame(deliver);
      }
    };

    const eventNames = [
      "turbo:load",
      "turbo:render",
      "pjax:end",
      "popstate",
      "hashchange",
    ];

    for (const eventName of eventNames) {
      window.addEventListener(eventName, schedule, true);
    }

    const navigation = (window as WindowWithNavigation).navigation;
    navigation?.addEventListener("navigatesuccess", schedule);

    // Fallback for GitHub navigation mechanisms that do not emit a public
    // event. Mutations only trigger a URL comparison; callback remains deduped.
    const observer = new MutationObserver(schedule);
    observer.observe(document, { childList: true, subtree: true });

    schedule();

    return (): void => {
      observer.disconnect();
      for (const eventName of eventNames) {
        window.removeEventListener(eventName, schedule, true);
      }
      navigation?.removeEventListener("navigatesuccess", schedule);
    };
  }

  async function handleNavigation({ url }: NavigationEvent): Promise<void> {
    if (url.hostname !== "github.com" || !JOB_PATH.test(url.pathname)) return;

    const stepsUrl = document.querySelector('[data-job-steps-url]')!.getAttribute("data-job-steps-url")!;

    const stepsRequest = await fetch(stepsUrl, {
      headers: {"Accept": "application/json"},
    });
    if (!stepsRequest.ok) {
      throw new Error(`Steps request failed with HTTP ${stepsRequest.status}`);
    }
    const steps = await stepsRequest.json() as JobStep[];

    const stepResponses: Array<Promise<Response>> = [];
    for (const step of steps) {
      stepResponses.push(fetch(step.log_url, {
        headers: {"Range": `bytes=-${INITIAL_LOAD_SIZE}`},
      }));
    }
    for (let i = 0; i < steps.length; i++) {
      steps[i].length = stepResponses[i].then((response) => contentRange(response).total);
      steps[i].contentByLine = stepResponses[i].then(parseLogResponse);
    }

    console.info("Steps are", steps);
  }

  onNavigation(handleNavigation);
})();
